---
abstract: 'Some common validator methods'
author:
  - 'Lenz Gschwendtner, C<< <norbu09 at cpan.org> >>'
  - 'Lenz Gschwendtner <norbu09@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Validate-Common
no_index:
  directory:
    - inc
    - t
requires:
  Any::Moose: 0
  Data::Validate::Domain: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.1
